In [3]:
flask_string ='''
Flask,   Z
T25,  ~1880
T75,  ~2624
T175,  ~2789
'''
import io
import pandas as pd
df_flasks = pd.read_csv(io.StringIO(flask_string))

In [10]:
dish_string ='''
Dish,   Z
150 mm,  ~2150
'''
import io
import pandas as pd
df_dishes = pd.read_csv(io.StringIO(dish_string))

In [11]:
well_plates_string ='''
Dish,   Z
96-well,  ~3262
'''
import io
import pandas as pd
df_wellplates = pd.read_csv(io.StringIO(well_plates_string))

In [12]:
from IPython.display import display, HTML
display(HTML('<b>ZOE GUIDE</b>'))
display(HTML('<b>Z values for Flasks:</b>'))
display(df_flasks)
display(HTML('<b>Z values for Dishes:</b>'))
display(df_dishes)
display(HTML('<b>Z values for Well Plates:</b>'))
display(df_wellplates)

  Flask        Z
0   T25    ~1880
1   T75    ~2624
2  T175    ~2789

     Dish        Z
0  150 mm    ~2150

      Dish        Z
0  96-well    ~3262